# Generated by Django 6.0.3 on 2026-04-05 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('FUEL', 'Паливо'), ('GOODS', 'Товари'), ('SUPPLIES', 'Витратні матеріали')], max_length=20)),
                ('quantity_requested', models.FloatField()),
                ('priority', models.IntegerField(choices=[(1, 'Нормальний'), (2, 'Підвищений'), (3, 'Критичний')], default=1)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.deliverypoint')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('FUEL', 'Паливо'), ('GOODS', 'Товари'), ('SUPPLIES', 'Витратні матеріали')], max_length=20)),
                ('quantity', models.FloatField(default=0.0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.warehouse')),
            ],
        ),
    ]
