# Generated by Django 6.0.3 on 2026-04-05 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-priority', '-is_urgent', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('warehouse', 'resource_type')},
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='deliverypoint',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Довгота'),
        ),
        migrations.AddField(
            model_name='request',
            name='quantity_allocated',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='actual_quantity',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Фактична кількість'),
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Зарезервовано'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='deliverypoint',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Назва об'єкта"),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Терміновий запит'),
        ),
        migrations.AlterField(
            model_name='request',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Нормальний'), (2, 'Підвищений'), (3, 'Критичний')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity_requested',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Очікує'), ('ALLOCATED', 'Розподілено'), ('SHIPPED', 'Відправлено'), ('COMPLETED', 'Доставлено'), ('CANCELLED', 'Скасовано')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Назва об'єкта"),
        ),
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.FloatField(default=0.0)),
                ('new_quantity', models.FloatField(default=0.0)),
                ('reason', models.TextField(default='Зміна попиту', verbose_name='Причина')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.request')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.request')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.warehouse')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
