# Generated by Django 6.0.3 on 2026-04-05 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_request_options_alter_stock_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('FUEL', 'Паливо'), ('GOODS', 'Товари'), ('SUPPLIES', 'Витратні матеріали')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('ALLOCATION', 'Виділення зі складу'), ('PREEMPT_OUT', 'Списання на перерозподіл'), ('PREEMPT_IN', 'Отримання через перерозподіл'), ('SHORTAGE', 'Нестача ресурсу')], max_length=20)),
                ('quantity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('from_location', models.CharField(blank=True, default='', max_length=255)),
                ('to_location', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
