# Generated by Django 6.0.3 on 2026-04-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resourcetransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Назва об'єкта")),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Місто')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Широта')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Довгота')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='request',
            name='resource_type',
            field=models.CharField(choices=[('FUEL', 'Паливо'), ('GOODS', 'Товари'), ('SUPPLIES', 'Витратні матеріали')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='resource_type',
            field=models.CharField(choices=[('FUEL', 'Паливо'), ('GOODS', 'Товари'), ('SUPPLIES', 'Витратні матеріали')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resourcetransaction',
            name='resource_type',
            field=models.CharField(choices=[('FUEL', 'Паливо'), ('GOODS', 'Товари'), ('SUPPLIES', 'Витратні матеріали')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resourcetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ALLOCATION', 'Виділення зі складу'), ('PREEMPT_OUT', 'Списання на перерозподіл'), ('PREEMPT_IN', 'Отримання через перерозподіл'), ('SHORTAGE', 'Нестача ресурсу')], db_index=True, max_length=20),
        ),
    ]
