# Generated by Django 6.0.3 on 2026-04-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employeeprofile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(('role', 'DISPATCHER'), ('delivery_point__isnull', True), ('warehouse__isnull', True), _connector='AND') | ~models.Q(('role', 'DISPATCHER')),
                name='employee_profile_dispatcher_has_no_bindings',
            ),
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(('role', 'DELIVERY_POINT_MANAGER'), ('delivery_point__isnull', False), ('warehouse__isnull', True), _connector='AND') | ~models.Q(('role', 'DELIVERY_POINT_MANAGER')),
                name='employee_profile_point_manager_has_delivery_point_only',
            ),
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.CheckConstraint(
                condition=models.Q(('role', 'WAREHOUSE_MANAGER'), ('warehouse__isnull', False), ('delivery_point__isnull', True), _connector='AND') | ~models.Q(('role', 'WAREHOUSE_MANAGER')),
                name='employee_profile_warehouse_manager_has_warehouse_only',
            ),
        ),
    ]
